language: node_js
node_js:
  - "6"
  - "4"

# possible fix for bcrypt install failing on Travis CI
# https://www.serverpals.com/blog/installing-bcrypt-on-travis-ci-with-node-4.x

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - CXX=g++-4.8
