before_script:
  - mysql -e 'DROP DATABASE IF EXISTS bitstarter_test; CREATE DATABASE bitstarter_test; GRANT ALL ON bitstarter_test.* TO 'bitstarter_test'@'localhost' IDENTIFIED BY 'password';'

language: node_js
node_js:
  - "6"
  - "4"

env:
  - BITSTARTER_DB_HOST="127.0.0.1" BITSTARTER_DB_PORT="3306" BITSTARTER_DB_USER="bitstarter_test" BITSTARTER_DB_PASS="password" BITSTARTER_DB_NAME="bitstarter_test"
